### ISSUE TITLE
MockingJay not found at execution

### ISSUE THREAD

**Issue by Bathilde** [banjun/Toki#2]
Hello,

I have made a simple application to test your pod and I have this error at execution:

`
dyld: Library not loaded: @rpath/XCTest.framework/XCTest
  Referenced from: /private/var/containers/Bundle/Application/704380AD-598D-4017-B4C3-F52B8381B688/TestSoap.app/Frameworks/Mockingjay.framework/Mockingjay
  Reason: image not found
`

My project is using Swift3 and it targets iOs 8. I also added Mockingjay in my Podfile and it does not works.

I can send the project if it helps.

**Comment by banjun** [comment]
post your `Podfile` content here.
what version of pods Toki and WSDL2Swift? (in your `Podfile.lock`)

**Comment by Bathilde** [comment]
I have the following Podfile:

`
use_frameworks!

target 'TestSoap' do
  pod 'Mockingjay'
  pod 'Toki'
end

target 'TestSoapTests' do
  pod 'Mockingjay'
  pod 'Toki'
end
`

Mockingjay has version 2.0.0 and Toki 0.9.0

At first I was only included Toki and it didn't work as well.

**Comment by banjun** [comment]
@Bathilde If  `TestSoap` is an app target, it does not need Toki nor Mockingjay. Try remove the pods from the app target.
Maybe only TestSoapTests are linked with XCTest, Toki and Mockingjay can live only there.

**Comment by Bathilde** [comment]
Yes TestSoap is an app target, except it needs at least Toki to work because it calls SOAP web services.

Edit: Ok, I go it. Toki and Mockingjay are only here to generate the class, I don't need them for code execution.
The only pod I need is WSDL2Swift!
